Sprint5
ClevertecFrontendLab/byshlata pull request #3
Opened 2023-03-06 14:05 UTC by byshlata

2023-03-06 14:10 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 20.
Количество непройденных тестов: 1.
***
**authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**error reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/error%20reset%20password.png)
***
**first enter.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/first%20enter.png)
***
**incorrect logit or password error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/incorrect%20logit%20or%20password%20error.png)
***
**loader authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/loader%20authorization.png)
***
**password hidden.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/password%20hidden.png)
***
**password shown.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/password%20shown.png)
***
**recovery page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/recovery%20page.png)
***
**registration already used error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/registration%20already%20used%20error.png)
***
**registration error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/registration%20error.png)
***
**registration page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/registration%20page.png)
***
**registration-first-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/registration-first-step.png)
***
**registration-second-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/registration-second-step.png)
***
**registration-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/registration-success.png)
***
**registration-third-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/registration-third-step.png)
***
**send email error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/send%20email%20error.png)
***
**send email success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/send%20email%20success.png)
***
**server error authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/server%20error%20authorization.png)
***
**success reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678111818/success%20reset%20password.png)

2023-03-06 17:02 UTC, dariavorom requested changes

2023-03-06 17:02 UTC, dariavorom commented on src/utils/highlight-text-search.tsx
> +import uuid from 'react-uuid';
а еще ты на 5 спринте уже, а шрифт так и не макету) надо уже подключить)

2023-03-07 08:02 UTC, byshlata commented on src/utils/highlight-text-search.tsx
> +import uuid from 'react-uuid';
да, тут согласен, протупил

2023-03-07 08:02 UTC, byshlata commented on package.json
> +    "@types/react-text-mask": "^5.4.11",
ок

2023-03-07 08:04 UTC, byshlata commented on src/components/form/form-auth/form-auth.tsx
> +    const [ isOtherErrorAPI, setOtherErrorAPI ] = useState<boolean>(false)
согласен

2023-03-07 08:04 UTC, byshlata commented on src/components/form/form-auth/form-auth.tsx
> +                    <ButtonText disabled={ !isValid } name={ TITLE_BUTTON } type='submit'
Сделаю как нужно.

2023-03-07 08:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 20.
Количество непройденных тестов: 0.
***
**error reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/error%20reset%20password.png)
***
**first enter.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/first%20enter.png)
***
**incorrect logit or password error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/incorrect%20logit%20or%20password%20error.png)
***
**loader authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/loader%20authorization.png)
***
**password hidden.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/password%20hidden.png)
***
**password shown.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/password%20shown.png)
***
**recovery page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/recovery%20page.png)
***
**registration already used error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/registration%20already%20used%20error.png)
***
**registration error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/registration%20error.png)
***
**registration page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/registration%20page.png)
***
**registration-first-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/registration-first-step.png)
***
**registration-second-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/registration-second-step.png)
***
**registration-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/registration-success.png)
***
**registration-third-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/registration-third-step.png)
***
**send email error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/send%20email%20error.png)
***
**send email success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/send%20email%20success.png)
***
**server error authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/server%20error%20authorization.png)
***
**success reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1678178782/success%20reset%20password.png)

2023-03-07 09:11 UTC, merged

2023-03-07 09:11 UTC, byshlata commented
Спасибо за проверку