Sprint7
ClevertecFrontendLab/byshlata pull request #5
Opened 2023-03-24 17:58 UTC by byshlata

2023-03-24 18:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 76%.
Общее количество тестов: 84.
Количество непройденных тестов: 9.

2023-03-24 18:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 74%.
Общее количество тестов: 98.
Количество непройденных тестов: 25.

2023-03-25 23:39 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 25.
Количество непройденных тестов: 1.
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/19-profile-avatar-after.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/25-1440-history.png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679787543/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20fail%20(failed).png)

2023-03-25 23:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679788022/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-26 10:05 UTC, SergeyGlazun requested changes

2023-03-26 10:05 UTC, SergeyGlazun commented on src/components/header/header.tsx
>          <StyledFlexContainer width="100%">
![image](https://user-images.githubusercontent.com/70904466/227768454-cc36eda9-f6e5-4cd2-9808-c2fdde3010c5.png)
при изменни оценки ошибка, стабильно воспроизводиться баг

2023-03-26 10:05 UTC, SergeyGlazun commented on src/components/header/header.tsx
>              </StyledFlexContainer>
![image](https://user-images.githubusercontent.com/70904466/227768567-0ba93161-6c1a-4c1b-92e5-442f4dcc47a4.png)
бургер не по макету

2023-03-26 10:45 UTC, byshlata commented on src/components/menu/menu-tablet/menu-tablet.tsx
> +    // useEffect(() => {
тут максимально не понял, так как у меня этих строчек уже не было, когда я отправля последние сохрания ночью.

2023-03-26 10:50 UTC, byshlata commented on src/components/header/header.tsx
>              </StyledFlexContainer>
не совсем понял, не правильна сама иконка или все меню?

2023-03-26 11:37 UTC, byshlata commented on src/components/header/header.tsx
> +export const Header = () => (
поправил

2023-03-26 12:20 UTC, byshlata commented on src/components/header/header.tsx
> -const avatar = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJUvqil3JW88xRn1y6uaPApcgpsprS47OAg&usqp=CAU'
В пятом стринте, иконки не дождно было быть, если мы не в поле, там был тест. Но поправил, раз уж тут по другому.

2023-03-26 12:59 UTC, byshlata commented on src/components/comment/types/comment-type.ts
> -import { PersonCommentType } from 'components/person-comment/types/person-comment-type';
если это при отпровлении комментария, то заблокировал кнопку, а так не совсем понятно, где. Не могли бы вы более радзвернто писать замечания, не всегда понятно, спасибо

2023-03-26 13:00 UTC, byshlata commented on src/components/header/header.tsx
>  import React from 'react';
у меня вроде как всегда грузяться, но поправил место, где может, что-то влиять.

2023-03-26 13:02 UTC, byshlata commented on src/components/header/header.tsx
не совсем понял, что за рамка, но тут поправил, у меня просто не было этого функционала, только из истории можно было менять

2023-03-26 14:01 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 67%.
Общее количество тестов: 75.
Количество непройденных тестов: 9.

2023-03-26 14:18 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 45%.
Общее количество тестов: 61.
Количество непройденных тестов: 16.

2023-03-26 14:25 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 6%.
Общее количество тестов: 29.
Количество непройденных тестов: 23.

2023-03-26 14:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 84.
Количество непройденных тестов: 10.

2023-03-26 15:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 84.
Количество непройденных тестов: 10.

2023-03-26 15:22 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 31%.
Общее количество тестов: 43.
Количество непройденных тестов: 12.

2023-03-26 15:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 73%.
Общее количество тестов: 84.
Количество непройденных тестов: 12.

2023-03-26 15:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 51%.
Общее количество тестов: 57.
Количество непройденных тестов: 7.

2023-03-26 16:05 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 67%.
Общее количество тестов: 80.
Количество непройденных тестов: 14.

2023-03-26 16:25 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679847956/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-26 16:50 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679849442/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 16:55 UTC, SergeyGlazun requested changes

2023-03-26 16:55 UTC, SergeyGlazun commented on src/components/book-content-wrapper/book-content-wrapper.tsx
>                  { element }
![image](https://user-images.githubusercontent.com/70904466/227790550-e156ee8d-6bbf-48ab-82fa-9c469ccde9d4.png)
жму вход пропадает сообщения о ошибки валидации

2023-03-26 16:55 UTC, SergeyGlazun commented on src/components/book-content-wrapper/book-content-wrapper.tsx
> -
![image](https://user-images.githubusercontent.com/70904466/227790617-66613479-6e1d-4cd3-892f-893b0f68eeed.png)
нет ошибки валидации

2023-03-26 16:55 UTC, SergeyGlazun commented on src/components/book-content-wrapper/book-content-wrapper.tsx
>  }
![image](https://user-images.githubusercontent.com/70904466/227790726-8b9a5648-3436-4faa-b0bd-300b26b61755.png)
не правильные данные в авторизации и улетел запрос

2023-03-26 16:55 UTC, SergeyGlazun commented on src/components/book-content-wrapper/book-content-wrapper.tsx
>  }
![image](https://user-images.githubusercontent.com/70904466/227790844-9e416912-896b-4e5f-954e-a800158f1692.png)
при редактировании тут не должно быть загушки иначе она улетит на сервер

2023-03-26 16:55 UTC, SergeyGlazun commented on src/components/book-content-wrapper/book-content-wrapper.tsx
>  }
в профиле

2023-03-26 16:55 UTC, SergeyGlazun commented on src/components/button/button-burger/button-burger.tsx
>  import React from 'react';
![image](https://user-images.githubusercontent.com/70904466/227791082-d3b972f6-f7fa-46d3-9b1e-709b4bf8086a.png)
сообщение после загрузки должно быть

2023-03-26 16:55 UTC, SergeyGlazun commented on src/components/button/button-burger/button-burger.tsx
>  import { DataTestId } from 'enum';
![image](https://user-images.githubusercontent.com/70904466/227791320-7a63e050-9d1d-4bf4-bfe2-b130045e8edb.png)
активны все книги пусто , возможно идет загрузка тогда нужно отоброзить лодером

2023-03-26 17:02 UTC, byshlata commented on src/components/book-content-wrapper/book-content-wrapper.tsx
> -
в задании было написано, что данные на вход не валидипуются, не я это придумал

2023-03-26 17:05 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679850345/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 17:26 UTC, byshlata commented on src/components/book-content-wrapper/book-content-wrapper.tsx
>  }
по логике, которая была в условии, у нас эти поня не валидируюся, а просто отправляется запрос, если он возвращается с ошибкой, мы выдаем hint не верный логин или пароль. 
второе - забил пароль, т.к. не проходили без него тесты 7го спринта.

2023-03-26 17:58 UTC, byshlata commented on src/components/button/button-burger/button-burger.tsx
>  import React from 'react';
я не знаю как что тут вам сказать, тогика у меня такая:
1. идет запрос на изменение оценки, если он положительный, то отображается алерт
2. если запрос на изменение ошибки положительный, то по тегу срабатывает запрос на обновление книги (что и происходит у вас на слайде)
3. логика работы лаодара у меня такая, что если есть хоть один активны запрос он крутиться,  а не включаеся-выключается.
4. так как сегодня максимально тупят запросы на  взятие конкретной книги, то вот так и выходит(я 4 часа пытался залить тесты повторно, т.к. не проходили запросы за конктретными книгами)

2023-03-26 18:02 UTC, byshlata commented on src/components/button/button-burger/button-burger.tsx
>  import { DataTestId } from 'enum';
поправил, вроде как. но я юзаю  RTK Query, поэтому там есть небольшая щадержка, которую вроде как поправил уже -  refetchOnMountOrArgChange

2023-03-26 18:12 UTC, byshlata commented on src/components/button/button-burger/button-burger.tsx
>  import React from 'react';
я мог бы дождаться конца запроса на обновление книги, но у него может быть ошибка, и тогода на экране будет 2 алерта.

2023-03-26 18:30 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679855430/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-26 19:51 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 25.
Количество непройденных тестов: 1.
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679860283/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679860283/19-profile-avatar-after.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679860283/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679860283/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679860283/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679860283/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679860283/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679860283/25-1440-history.png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679860283/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 20:10 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 93%.
Общее количество тестов: 98.
Количество непройденных тестов: 6.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679861441/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-26 20:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679863101/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-26 20:55 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 93%.
Общее количество тестов: 98.
Количество непройденных тестов: 6.
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- test not foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/Sprint%202%20--%20slider%20tests%20--%20test%20not%20foto%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- update-review-book-page -- crate-button-name (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679864108/Sprint%207%20--%20Profile%20functions%20tests%20--%20update-review-book-page%20--%20crate-button-name%20(failed).png)

2023-03-26 21:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 92%.
Общее количество тестов: 98.
Количество непройденных тестов: 7.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679865469/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 21:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 92%.
Общее количество тестов: 98.
Количество непройденных тестов: 7.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679866634/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 21:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679867398/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 22:50 UTC, ValadzkoAliaksei commented on .eslintrc.js
> +    ignorePatterns: ['coverage', 'cypress.config.ts', 'src/components/alert-message/*', 'src/store/slice/*', 'src/components/menu/menu-mini/hooks/use-menu-mini.ts'],
![image](https://user-images.githubusercontent.com/61273546/227809444-44733fa9-2056-495f-8efc-96e5cb3a4492.png)
Не удаляется бронь, id-шник не тот

2023-03-26 22:50 UTC, ValadzkoAliaksei commented on cypress.config.ts
> +        experimentalSessionAndOrigin: true,
![image](https://user-images.githubusercontent.com/61273546/227809548-e3a677d0-7891-4166-b3fb-5869ba047b98.png)
стрелка вниз в календаре не работает(

2023-03-26 22:50 UTC, ValadzkoAliaksei commented on package.json
> +    "eslint": "8.22.0",
![image](https://user-images.githubusercontent.com/61273546/227809616-a8ad91a5-8fa7-4d76-a268-e24ee01e6e7c.png)
отменил бронь в странице книги, зашел в профиль, а бронь всё равно висит.
Нужен запрос за пользаком для обновления данных

2023-03-26 22:50 UTC, SergeyGlazun commented on src/components/book-content-wrapper/book-content-wrapper.tsx
> -
![image](https://user-images.githubusercontent.com/70904466/227809716-d3e67dc5-3a7e-4717-a996-dc476ed0db84.png)

2023-03-26 22:54 UTC, SergeyGlazun commented on src/components/book-content-wrapper/book-content-wrapper.tsx
>  }
вы отправите пароль не тот который у пользователя. Пользователь после этого больше не зайдет на страницу.

2023-03-26 22:56 UTC, SergeyGlazun commented on src/components/button/button-burger/button-burger.tsx
>  import React from 'react';
на макете дождались покамесь отработали все запросы потом появилось одно уведомление уведомление. Подумайте как так сделать

2023-03-26 23:06 UTC, SergeyGlazun requested changes

2023-03-26 23:06 UTC, SergeyGlazun commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
> +    useEffect(() => {
![image](https://user-images.githubusercontent.com/70904466/227810199-e4ec854a-2b0e-44c3-918a-195c3035c784.png)
![image](https://user-images.githubusercontent.com/70904466/227810207-0e4db29d-40d4-44d8-aae7-911c06ab86f0.png)
книга забронирована а тут ее нет

2023-03-26 23:06 UTC, SergeyGlazun commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
> +        if(!isChanged) {
![image](https://user-images.githubusercontent.com/70904466/227810360-a379a5f8-202b-429b-8f6e-139b154b537e.png)
куда-то пропадает чуть словил на скрине

2023-03-26 23:06 UTC, SergeyGlazun commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
> +            setValue(NameInput.Password, '')
![image](https://user-images.githubusercontent.com/70904466/227810399-76076687-0741-46a1-8b8a-76f34119916d.png)
2 списка

2023-03-26 23:06 UTC, SergeyGlazun commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
> +        } else {
![image](https://user-images.githubusercontent.com/70904466/227810454-1356df23-11fe-4c30-a849-a6a4ae51554e.png)
тот же баг что был

2023-03-26 23:23 UTC, byshlata commented on cypress.config.ts
> +        experimentalSessionAndOrigin: true,
поправил

2023-03-26 23:24 UTC, byshlata commented on .eslintrc.js
> +    ignorePatterns: ['coverage', 'cypress.config.ts', 'src/components/alert-message/*', 'src/store/slice/*', 'src/components/menu/menu-mini/hooks/use-menu-mini.ts'],
поправил

2023-03-26 23:47 UTC, byshlata commented on package.json
> +    "eslint": "8.22.0",
поправил

2023-03-26 23:56 UTC, byshlata commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
> +        } else {
я ж уже писал, что не было такого в условиях, тест не проходит, если ее заблокировать.

2023-03-26 23:57 UTC, byshlata commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
> +        if(!isChanged) {
увеличил вреня задержки

2023-03-26 23:57 UTC, byshlata commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
> +    useEffect(() => {
тут поправил

2023-03-27 00:02 UTC, byshlata commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
> +            setValue(NameInput.Password, '')
поправил

2023-03-27 00:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679875499/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-27 00:33 UTC, byshlata commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
поправил

2023-03-27 00:39 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 25.
Количество непройденных тестов: 0.
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/19-profile-avatar-after.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679877567/25-1440-history.png)

2023-03-27 00:39 UTC, SergeyGlazun commented on src/components/form/form-chage-user-information/form-change/form-change.tsx
> +        } else {
да и правда в 5 спринте было такое условие лучше кидайте ссылку или скрин

2023-03-27 00:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878066/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-27 00:50 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679878235/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-27 01:13 UTC, SergeyGlazun requested changes

2023-03-27 01:13 UTC, SergeyGlazun commented on src/components/calendar/calendar.tsx
>      }
![image](https://user-images.githubusercontent.com/70904466/227817764-03643234-3859-4edc-bb2b-1b7b0d1baa4a.png)
окна успеха/ ошибки после всех загрузок

2023-03-27 01:13 UTC, SergeyGlazun commented on src/components/calendar/calendar.tsx
>      const onChangeMonth = (indexMonth: ChangeMonthIndex) => {
![image](https://user-images.githubusercontent.com/70904466/227817850-9e5e20ab-777c-445d-98b9-1ef255b4f8d5.png)
скроллов быть не должно горизонтальных

2023-03-27 01:29 UTC, byshlata commented on src/components/calendar/calendar.tsx
>      }
builder.addMatcher(API.endpoints.changeDataUser.matchFulfilled, (state) => {
                state.isProgress = false;
                state.errorMessage = {
                    type: 'success',
                    message: ErrorAndMessageApi.MessageChangeDataUser
                }
            })
вот так у меня сейчас, но ничего не поменялось по моему, других запросов в это время нет, я поверил. SetTimeout ставить что ли?

2023-03-27 01:38 UTC, byshlata commented on src/components/calendar/calendar.tsx
>      const onChangeMonth = (indexMonth: ChangeMonthIndex) => {
поправил.

2023-03-27 01:41 UTC, byshlata commented on src/components/calendar/calendar.tsx
>      }
Можно бы было сделать задержку на алерте, но тогда не проходят тесты частяком, я пробовал как-то

2023-03-27 02:05 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 6 -- booking and book rate -- booking modal -- check booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20modal%20--%20check%20booking%20request%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679882744/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-27 02:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- update-review-book-page -- crate-button-name (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679883853/Sprint%207%20--%20Profile%20functions%20tests%20--%20update-review-book-page%20--%20crate-button-name%20(failed).png)

2023-03-27 05:41 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679895715/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-27 06:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 94%.
Общее количество тестов: 98.
Количество непройденных тестов: 5.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 6 -- booking and book rate -- booking modal -- check booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20modal%20--%20check%20booking%20request%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679896851/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)

2023-03-27 06:39 UTC, SergeyGlazun approved these changes

2023-03-27 06:43 UTC, SergeyGlazun commented
проект  в целом норм делаю скидку что понедельник всем на работу

2023-03-27 07:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 92%.
Общее количество тестов: 98.
Количество непройденных тестов: 7.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679901407/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)

2023-03-27 07:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 92%.
Общее количество тестов: 98.
Количество непройденных тестов: 7.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1679902646/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-27 09:23 UTC, ValadzkoAliaksei approved these changes

2023-03-27 09:29 UTC, byshlata commented
Спасибо за проверку

2023-03-27 09:30 UTC, merged